Add `react-router-dom` package
Due to the way `npm` solves peer dependencies, we were able to import
`react-router-dom` in the project even when we didn't have it as
dependency. After switching to `pnpm` this bug appeared:

```
Error: Cannot find module 'react-router-dom' imported from
'app/routes/docs.$lang.$ref.tsx'
```